const names = [
  "Alice",
  "Bob",
  "Charlie",
  "Frank ",
  "Darabont",
  "Clancy Brown",
  "Gil Bellows",
  "Mario Puzo",
  "Michael Corleone",
  "Andy Dufresne",
  "Red Redding",
  "Vito Corleone",
  "Michael Corleone",
  "Bruce Wayne",
  "James Gordon",
  "Harvey Dent",
  "Oskar Schindler",
  "Amon Göth",
  "Clarice Starling",
  "Hannibal Lecter",
  "William Somerset",
  "David Mills",
  "Roger Kint",
  "Forrest Gump",
  "Jenny Curran",
  "Maximus Decimus Meridius",
  "Commodus",
  "Simba",
  "Scar",
];

export default names;
